Set psycopg2_binary version requirement not strict
greenplum-db/GreenplumPython pull request #183
Opened 2023-03-07 17:02 UTC by Quasimewdo

Previously in `requirements.txt`, `psycopg2_binary==2.9.5`. 
This patch removes the strict version requirement and changes 
it to `2.9.*` to meet more possibility of versions.

2023-03-08 02:10 UTC, yihong0618 approved these changes

2023-03-08 06:15 UTC, beeender requested changes
Actually using the specific dependency version is on purpose -- to make sure the CI gives us a consistent result at a specific SHA1. 

If there is a need to bump the dependency version, just make a commit to bump it. I would like to avoid wildcard in the requirement.txt.

Does `2.9.5` have any problem?

2023-03-08 08:46 UTC, Quasimewdo commented
> Actually using the specific dependency version is on purpose -- to make sure the CI gives us a consistent result at a specific SHA1.
> 
> If there is a need to bump the dependency version, just make a commit to bump it. I would like to avoid wildcard in the requirement.txt.
> 
> Does `2.9.5` have any problem?

Well there is ask to build the package with `conda`, but the latest version of `psycopg2`-binary in `conda` is 2.9.3, so can't build it.

2023-03-09 02:29 UTC, beeender commented
> > Actually using the specific dependency version is on purpose -- to make sure the CI gives us a consistent result at a specific SHA1.
> > If there is a need to bump the dependency version, just make a commit to bump it. I would like to avoid wildcard in the requirement.txt.
> > Does `2.9.5` have any problem?
> 
> Well there is ask to build the package with `conda`, but the latest version of `psycopg2`-binary in `conda` is 2.9.3, so can't build it.

I was wrong, the `requirements.txt` is more about how user install it, but not what will be released.

This is OK.

2023-03-09 02:30 UTC, beeender approved these changes

2023-03-09 07:51 UTC, merged